image: ruby:2.3.1

services:

variables:
  GIT_STRATEGY: clone

cache:
  key: "$CI_PROJECT_PATH"
  paths:
    - vendor

before_script:
  - cp .env-example .env
  - source .env
  - export DEBIAN_FRONTEND=noninteractive
  - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true  
  - ruby -v

after_script:
  - ./scripts/notify_hipchat.sh

stages:
  - spec
  - check
  - audit
  - deploy
  - pages
  - cleanup

dev_spec_puppet:
  only:
    - branches
  except:
    - master
  stage: spec
  script:
    - gem install bundler  --no-ri --no-rdoc
    - bundle install -j $(nproc) --path vendor
    - bundle exec rake compute_dev_version
    - bundle exec rake clean
    - bundle exec rake clean_fixtures
    - bundle exec rake spec_clean
    - bundle exec rake spec_prep
  tags:
    - ruby
    - puppet

dev_rubocop:
  only:
  - branches
  except:
  - master
  stage: check
  script:
  - gem install bundler --no-ri --no-rdoc
  - bundle install -j $(nproc) --path vendor
  - bundle exec rake compute_dev_version
  - bundle exec rake rubocop
  dependencies:
  - dev_spec_puppet
  tags:
  - ruby
  - puppet

dev_checks:
  only:
  - branches
  except:
  - master
  stage: check
  script:
  - gem install bundler --no-ri --no-rdoc
  - bundle install -j $(nproc) --path vendor
  - bundle exec rake compute_dev_version
  - bundle exec rake check:dot_underscore
  - bundle exec rake check:git_ignore
  - bundle exec rake check:test_file
  - bundle exec rake check:symlinks
  dependencies:
  - dev_spec_puppet
  tags:
  - ruby
  - puppet

dev_release_checks:
  only:
  - branches
  except:
  - master
  stage: check
  script:
  - gem install bundler  --no-ri --no-rdoc
  - bundle install -j $(nproc) --path vendor
  - bundle exec rake release_checks
  dependencies:
  - dev_spec_puppet
  tags:
  - ruby
  - puppet

dev_audit:
  only:
  - branches
  except:
  - master
  stage: audit
  script:
  - gem install bundler  --no-ri --no-rdoc
  - bundle install -j $(nproc) --path vendor
  - 'bundle exec rake bundle:audit'
  dependencies:
  - dev_rubocop
  - dev_checks
  - dev_release_checks
  tags:
  - ruby
  - puppet

dev_build_puppet_module:
  only:
    - branches
  except:
    - master
  stage: deploy
  before_script:
  - apt-get update
  - apt-get -qq install python python-pip ca-certificates
  - pip install awscli
  script:
    - gem install bundler  --no-ri --no-rdoc
    - bundle install -j $(nproc) --path vendor
    - bundle exec rake build
    - aws s3 sync pkg/ s3://$S3_BUCKET
  dependencies:
  - dev_audit
  artifacts:
    paths:
    - pkg/
  tags:
    - ruby
    - puppet
  environment: development

# MASTER branch goes to production and triggers puppet pull
# MASTER Tests
release_checks:
  only:
    - master
  stage: spec
  script:
    - gem install bundler  --no-ri --no-rdoc
    - bundle install -j $(nproc) --path vendor
    - bundle exec rake spec_prep
    - bundle exec rake release_checks
  tags:
    - ruby
    - puppet

checks:
  only:
    - master
  stage: check
  script:
    - gem install bundler  --no-ri --no-rdoc
    - bundle install -j $(nproc) --path vendor
    - bundle exec rake spec_prep
    - 'bundle exec rake check:dot_underscore'
    - 'bundle exec rake check:git_ignore'
    - 'bundle exec rake check:test_file'
    - 'bundle exec rake check:symlinks'
  dependencies:
  - release_checks
  tags:
    - ruby
    - puppet

audit:
  only:
    - master
  stage: audit
  script:
    - gem install bundler  --no-ri --no-rdoc
    - bundle install -j $(nproc) --path vendor
    - bundle exec rake spec_prep
    - 'bundle exec rake bundle:audit'
  dependencies:
  - checks
  tags:
    - ruby
    - puppet

puppet_module:
  only:
    - master
  stage: deploy
  before_script:
  - apt-get update
  - apt-get -qq install python python-pip ca-certificates
  - pip install awscli
  script:
  - gem install bundler  --no-ri --no-rdoc
  - bundle install -j $(nproc) --path vendor
  - bundle exec rake build
  - aws s3 sync pkg/ s3://$S3_BUCKET
  dependencies:
  - audit
  artifacts:
    paths:
    - pkg/
  tags:
    - ruby
    - puppet
  environment: production
