image: ruby:2.3.1

services:

variables:
  GIT_STRATEGY: clone

cache:
  key: "$CI_PROJECT_PATH"
  paths:
    - vendor

before_script:
  - cp .env-example .env
  - source .env
  - export DEBIAN_FRONTEND=noninteractive
  - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - ruby -v

after_script:
  - ./scripts/notify_hipchat.sh

stages:
  - spec
  - check
  - audit
  - deploy
  - pages
  - cleanup

spec_puppet:
  stage: spec
  script:
    - gem install bundler  --no-ri --no-rdoc
    - bundle install -j $(nproc) --path vendor
    - bundle exec rake compute_dev_version
    - bundle exec rake clean
    - bundle exec rake clean_fixtures
    - bundle exec rake spec_clean
    - bundle exec rake spec_prep
  tags:
  - UBEROPS
  - puppet
  - aws

release_checks:
  stage: spec
  script:
    - gem install bundler  --no-ri --no-rdoc
    - bundle install -j $(nproc) --path vendor
    - bundle exec rake spec_prep
    - bundle exec rake release_checks
  tags:
  - UBEROPS
  - puppet
  - aws

rubocop:
  stage: check
  script:
  - gem install bundler --no-ri --no-rdoc
  - bundle install -j $(nproc) --path vendor
  - bundle exec rake compute_dev_version
  - bundle exec rake rubocop
  dependencies:
  - spec_puppet
  - release_checks
  tags:
  - UBEROPS
  - puppet
  - aws

checks:
  stage: check
  script:
    - gem install bundler  --no-ri --no-rdoc
    - bundle install -j $(nproc) --path vendor
    - bundle exec rake spec_clean
    - 'bundle exec rake check:dot_underscore'
    - 'bundle exec rake check:git_ignore'
    - 'bundle exec rake check:test_file'
    - 'bundle exec rake check:symlinks'
  dependencies:
  - spec_puppet
  - release_checks
  tags:
  - UBEROPS
  - puppet
  - aws

audit:
  stage: audit
  script:
    - gem install bundler  --no-ri --no-rdoc
    - bundle install -j $(nproc) --path vendor
    - bundle exec rake spec_prep
    - 'bundle exec rake bundle:audit'
  dependencies:
  - checks
  - rubocop
  tags:
  - UBEROPS
  - puppet
  - aws

master:
  only:
    - master
  stage: deploy
  before_script:
  - cp .env-example .env
  - source .env
  - export DEBIAN_FRONTEND=noninteractive
  - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - ruby -v
  - apt-get update
  - apt-get -qq install python python-pip ca-certificates
  - pip install awscli
  script:
  - gem install bundler  --no-ri --no-rdoc
  - bundle install -j $(nproc) --path vendor
  - bundle exec rake build
  dependencies:
  - audit
  artifacts:
    paths:
    - pkg/
  tags:
  - UBEROPS
  - puppet
  - aws
  environment: master

production:
  only:
    - production
  stage: deploy
  before_script:
  - cp .env-example .env
  - source .env
  - export DEBIAN_FRONTEND=noninteractive
  - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - ruby -v
  - apt-get update
  - apt-get -qq install python python-pip ca-certificates
  - pip install awscli
  script:
  - gem install bundler  --no-ri --no-rdoc
  - bundle install -j $(nproc) --path vendor
  - bundle exec rake build
  dependencies:
  - audit
  artifacts:
    paths:
    - pkg/
  tags:
  - UBEROPS
  - puppet
  - aws
  environment: production

development:
  only:
    - development
  stage: deploy
  before_script:
  - cp .env-example .env
  - source .env
  - export DEBIAN_FRONTEND=noninteractive
  - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - ruby -v
  - apt-get update
  - apt-get -qq install python python-pip ca-certificates
  - pip install awscli
  script:
  - gem install bundler  --no-ri --no-rdoc
  - bundle install -j $(nproc) --path vendor
  - bundle exec rake build
  - aws s3 sync pkg/ s3://$S3_BUCKET/puppet/dvelopment
  dependencies:
  - audit
  artifacts:
    paths:
    - pkg/
  tags:
  - UBEROPS
  - puppet
  - aws
  environment: development

test:
  only:
    - test
  stage: deploy
  before_script:
  - cp .env-example .env
  - source .env
  - export DEBIAN_FRONTEND=noninteractive
  - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - ruby -v
  - apt-get update
  - apt-get -qq install python python-pip ca-certificates
  - pip install awscli
  script:
  - gem install bundler  --no-ri --no-rdoc
  - bundle install -j $(nproc) --path vendor
  - bundle exec rake build
  - aws s3 sync pkg/ s3://$S3_BUCKET/puppet/test
  dependencies:
  - audit
  artifacts:
    paths:
    - pkg/
  tags:
  - UBEROPS
  - puppet
  - aws
  environment: test

stable:
  only:
    - 2-0-stable
  except:
    - master
    - development
    - production
    - test
  stage: deploy
  before_script:
  - cp .env-example .env
  - source .env
  - export DEBIAN_FRONTEND=noninteractive
  - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - ruby -v
  - apt-get update
  - apt-get -qq install python python-pip ca-certificates
  - pip install awscli
  script:
  - gem install bundler  --no-ri --no-rdoc
  - bundle install -j $(nproc) --path vendor
  - bundle exec rake build
  - aws s3 sync pkg/ s3://$S3_BUCKET/puppet/stable
  dependencies:
  - audit
  artifacts:
    paths:
    - pkg/
  tags:
  - UBEROPS
  - puppet
  - aws
  environment: stable

beta:
  only:
    - branches
  except:
    - master
    - development
    - production
    - test
  stage: deploy
  before_script:
  - cp .env-example .env
  - source .env
  - export DEBIAN_FRONTEND=noninteractive
  - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - ruby -v
  - apt-get update
  - apt-get -qq install python python-pip ca-certificates
  - pip install awscli
  script:
  - gem install bundler  --no-ri --no-rdoc
  - bundle install -j $(nproc) --path vendor
  - bundle exec rake build
  dependencies:
  - audit
  artifacts:
    paths:
    - pkg/
  tags:
  - UBEROPS
  - puppet
  - aws
  environment: beta
